queue: Hosted VS2017

steps:

- checkout: self
  clean: true

- task: MSBuild@1
  displayName: Restore
  inputs:
    solution: build.proj
    msbuildArguments: /t:Restore /bl:"$(Build.ArtifactStagingDirectory)\restore.binlog"

- task: MSBuild@1
  displayName: Build
  inputs:
    solution: build.proj
    msbuildArguments: /t:Build /bl:"$(Build.ArtifactStagingDirectory)\build.binlog"

- task: MSBuild@1
  displayName: Push
  inputs:
    solution: build.proj
    msbuildArguments: /t:Push /p:StorageAccessKey=$(StorageAccessKey) /bl:"$(Build.ArtifactStagingDirectory)\push.binlog"

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: output
    ArtifactType: Container